### ISSUE TITLE
Fix spelling error (game **enine** -> engine)

### ISSUE THREAD

**Issue by aikenahac** [MaticBabnik/maticbabnik.github.io#1]
https://github.com/MaticBabnik/maticbabnik.github.io/blob/964d81a4f10464084b7fba89df75fdcd726b3a1d/index.html#L42

**Comment by MaticBabnik** [comment]
raj poslusej rpa/ppb

thx tho

**Comment by aikenahac** [comment]
Good thing da nerabm pr PPBv poslusat ker lah drugo delam :)
